- name: updating machine
  apt: name=* state=latest

- name: installing some dependencies
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items:
  - git
  - curl
  - vim
  - libssl0.9.8
  - libjna-java
  - sysstat
  - python-software-properties
